global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'service-techs'
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: 'service-requests'
    static_configs:
      - targets: ['host.docker.internal:8081']